### ISSUE TITLE
Not possible to use variable as zone name

### ISSUE THREAD

**Issue by ramilexe** [terraform-aws-modules/terraform-aws-route53#10]
Because zone name place as key terraform doesn't allow to use a variable for it. 

```
terraform plan

Error: Ambiguous attribute key

  on dns.tf line 6, in module "zones":
   6:     var.domain_name_com = {

If this expression is intended to be a reference, wrap it in parentheses. If
it's instead intended as a literal name containing periods, wrap it in quotes
to create a string literal.
```

**Comment by antonbabenko** [comment]
Hi, @ramilexe !

I am not sure I follow what you are trying to do.

The issue you have is not related to the module.

Please check out [example code](https://github.com/terraform-aws-modules/terraform-aws-route53/blob/master/examples/complete/main.tf) for more details on how to use this module.

For generic Terraform questions, please ask them on https://discuss.hashicorp.com/

**Comment by ramilexe** [comment]
You define zone name as a key, in your examples they are hardcoded for example `app.terraform-aws-modules-example.com`. in my case I have zone names defined as variable and based on environment (workspace). With your approach it is not possible to use

**Comment by antonbabenko** [comment]
This is related to Terraform, please ask this question in the forum.

**Comment by x80486** [comment]
I ran into the same issue. Without the possibility to refer to variables in the zone names this is almost useless because you have to know the value beforehand.

I know it's related to Terraform, but there could be a way to do it currently. Someone will do something like this almost all the time:

```hcl2
module "route53_zones" {
  source  = "terraform-aws-modules/route53/aws//modules/zones"
  version = "1.2.0"

  zones = {
    var.domain_name = {
      comment = "Managed by Terraform"

      tags = local.tags
    }
  }
}
```

**Comment by ramilexe** [comment]
@x80486 thank you for good explanation. Because of this issue this module doesn't make any sense.

**Comment by x80486** [comment]
If you enclose the variable in parentheses it works:

```hcl
module "route53_zones" {
  source  = "terraform-aws-modules/route53/aws//modules/zones"
  version = "1.2.0"

  zones = {
    (var.domain_name) = {
      comment = "Managed by Terraform"

      tags = local.tags
    }
  }
}
```

```shell
  ...
  # module.route53_zones.aws_route53_zone.this["domain.tld"] will be created
  + resource "aws_route53_zone" "this" {
      + comment       = "Managed by Terraform"
      + force_destroy = false
      + id            = (known after apply)
      + name          = "domain.tld"
      + name_servers  = (known after apply)
      + tags          = {
          + "Application" = "domain.tld"
          + "Environment" = "sandbox"
          + "Terraform"   = "true"
        }
      + zone_id       = (known after apply)
    }

Plan: 7 to add, 0 to change, 0 to destroy.
```

**Comment by ramilexe** [comment]
Wow, I didn't know it. I disappointed why author didn't suggested this solution and just closed the issue.

**Comment by antonbabenko** [comment]
@ramilexe Honestly, I didn't know this solution would work here 👍  Good that it works!

This is why for me it is much better to forward people's questions about Terraform to a designated place.

If anyone wants to help - open a valid PR updating documentation describing this fix. This kind of small fixes is very useful!
