### ISSUE TITLE
Private Zones not supported in the route53 zone module

### ISSUE THREAD

**Issue by hawkesnc** [terraform-aws-modules/terraform-aws-route53#15]
Taken from registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_zone#private-zone

This PR here will add that feature in: https://github.com/terraform-aws-modules/terraform-aws-route53/pull/13

**Comment by sebastianvoss** [comment]
Great, thanks for your effort. Hopefully it gets merged soon.

**Comment by antonbabenko** [comment]
Thanks @hawkesnc !

Fixed in #13. 

[v1.4.0](https://github.com/terraform-aws-modules/terraform-aws-route53/releases/v1.4.0) has been just released.
