### ISSUE TITLE
Route53 Record module does not support weighted_records

### ISSUE THREAD

**Issue by hawkesnc** [terraform-aws-modules/terraform-aws-route53#16]
Currently the route53 record module doesn't support `weighted_records`. 

Using a dynamic block would solve one part of the problem:
```
  dynamic "weighted_routing_policy" {
    for_each = length(keys(lookup(each.value, "weighted_routing_policy", {}))) == 0 ? [] : [true]

    content {
      weight = each.value.weighted_routing_policy.weight
    }
  }
```

Unfortunately, the `locals` calculated would produce non-unique keys as the `name` and `type` would be identical. Re-writing the `for` loop would produce unique keys:

`recordsets = { for idx, rs in var.records : "${rs.name} ${idx}" => rs }`

**Comment by nashvan** [comment]
I tested it this way works well without editing the for loop
```
dynamic "weighted_routing_policy" {
    for_each = length(keys(lookup(each.value, "weighted_routing_policy", {}))) == 0 ? [] : [true]

    content {
      weight                 = lookup(each.value.weighted_routing_policy,"weight", true)
    }
  }
```
