### ISSUE TITLE
There is no function named "object" (v0.13.3)

### ISSUE THREAD

**Issue by dennybaa** [terraform-aws-modules/terraform-aws-route53#17]
Error: Call to unknown function

  on .terraform/modules/coginto_route53/modules/records/main.tf line 15, in resource "aws_route53_record" "this":
  15:   for_each = var.create && (var.zone_id != null || var.zone_name != null) ? local.recordsets : object({})

There is no function named "object".

**Comment by dennybaa** [comment]
resolved by #14

**Comment by antonbabenko** [comment]
Fixed in #14.

[v1.5.0](https://github.com/terraform-aws-modules/terraform-aws-route53/releases/v1.5.0) has been just released.
