### ISSUE TITLE
The true and false result expressions must have consistent types. The given expressions are object and map of dynamic, respectively.

### ISSUE THREAD

**Issue by yuzujoe** [terraform-aws-modules/terraform-aws-route53#19]
I raised the version to 1.5.0 and got an error in the title.

It seems to have been changed from object to tomap at the time of false, but if you check the specification of tomap, you will find the following.

````
Since Terraform's concept of a map requires all of the elements to be of the same type, mixed-typed elements will be converted to the most general type
````

If this is correct then I think it would be an error because what is defined in bool is not of the correct type, but isn't this kind of problem happening?

Thanks

**Comment by antonbabenko** [comment]
Hi @yuzujoe !

Please check the examples code in [examples/complete](https://github.com/terraform-aws-modules/terraform-aws-route53/tree/master/examples/complete) and consider upgrading to the latest version of this module if possible.

This issue should have been resolved some time ago but if you still have it - make sure to include a code in the description of an issue.
