### ISSUE TITLE
Invalid for_each argument in v1.6.0

### ISSUE THREAD

**Issue by nabeelshaikh91** [terraform-aws-modules/terraform-aws-route53#24]
```
Error: Invalid for_each argument

  on .terraform/modules/records-private-ro/modules/records/main.tf line 15, in resource "aws_route53_record" "this":
  15:   for_each = var.create && (var.zone_id != null || var.zone_name != null) ? local.recordsets : tomap({})

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```
v1.5.0 works perfectly

**Comment by antonbabenko** [comment]
Hi @nabeelshaikh91 !

Please check the solution for a similar issue here - https://github.com/terraform-aws-modules/terraform-aws-route53/issues/25#issuecomment-778749402

Consider upgrading to the latest version of this module if possible, and check the examples code in [examples/complete](https://github.com/terraform-aws-modules/terraform-aws-route53/tree/master/examples/complete).
