### ISSUE TITLE
Wrong plan in second execution

### ISSUE THREAD

**Issue by MarwanBayadsi** [terraform-aws-modules/terraform-aws-route53#34]
Hi,

When executing Plan command for this module after first Apply (which passed successfully),   it will give wrong Plan output.
It tells that there's a change: 
vpc_id -> null
region -> null

Expected:   
Plan: 0 to add, 0 to change, 0 to destroy
Actual:
Plan: 0 to add, 1 to change, 0 to destroy

Are you aware about this issue ?

**Comment by antonbabenko** [comment]
Please open an issue with all the required details. It is not possible for us to guess what kind of configuration you have.

PS: Also, check code in examples folder.
