### ISSUE TITLE
zone_id and zone_name are not allowed to use together, have ability to use additional name

### ISSUE THREAD

**Issue by 7adityaraj** [terraform-aws-modules/terraform-aws-route53#41]
## Description

Providing zone_name as per module 'git@github.com:terraform-aws-modules/terraform-aws-route53.git//modules/records?ref=v2.0.0"' throws an error.

```
module "r53_record_public" {
  source         = "git@github.com:terraform-aws-modules/terraform-aws-route53.git//modules/records?ref=v2.0.0"
  zone_id        = var.r53_public_zone_id
  zone_name  = "${local.aws_tags.project}-${terraform.workspace}.${var.r53_public_zone_domain}"
 
 records = [{
    name = "${local.aws_tags.project}-${terraform.workspace}.${var.r53_public_zone_domain}"
    type = "A"
    alias = {
      name                   = module.cf_alb_distribution.cloudfront_distribution_domain_name
      zone_id                = module.cf_alb_distribution.cloudfront_distribution_hosted_zone_id
      evaluate_target_health = true
    }
  }]
}
```
As per TF doc, both cannot be used together.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/route53_zone

## Versions

 - Terraform: 0.13.4

 - Provider(s): aws 3.28.0

 - Module: 2.0.0

## Expected behavior

user should have the ability to input custom zone name which should not join with data "aws_route53_zone"

## Actual behavior

when we provide zone_name it returns an error

 `Error: zone_id and name arguments can't be used together.`

## Additional context

I am not sure if this is the correct approach, but when I tweaked the module and replace name as:

From:
 name            = each.value.name != "" ? "${each.value.name}.${data.aws_route53_zone.this[0].name}" : data.aws_route53_zone.this[0].name  

To:
name            = each.value.name != "" ? "${each.value.name}" : data.aws_route53_zone.this[0].name

This helped me to have the ability to input custom zone_name and hope if this is a right approach we can work on this bug.
I apologize if I missed providing more information and appreciate any further feedbacks.

**Comment by antonbabenko** [comment]
You just need to set one of these - `zone_name` or `zone_id`. Not both.

**Comment by 7adityaraj** [comment]
@antonbabenko thank you for your prompt response. What would be the way if we need to have a custom zone name, how we can override the value with the latest version of the module.

**Comment by antonbabenko** [comment]
What does a custom zone name mean? In any case, you just need to provide whatever you have - zone name or zone id.
