### ISSUE TITLE
Implement DNSSec 

### ISSUE THREAD

**Issue by jkroepke** [terraform-aws-modules/terraform-aws-route53#57]
## Is your request related to a new offering from AWS?
https://aws.amazon.com/de/about-aws/whats-new/2020/12/announcing-amazon-route-53-support-dnssec/

## Is your request related to a problem? Please describe.
No

## Describe the solution you'd like.
I would like to enable DNSSec on my public zones

## Describe alternatives you've considered.
Using raw terraform resources

## Additional context
It just nice to know, but adding dnssec could be a real benefit to this module

**Comment by antonbabenko** [comment]
I agree that this should be a rather handy addition to the module if implemented in a flexible way.

PR is welcome.
