### ISSUE TITLE
Unable to use module from git

### ISSUE THREAD

**Issue by sdmattheww** [terraform-aws-modules/terraform-aws-route53#58]
## Description

I'm trying to utilize this module by cloning it from git with https://

## Versions
Terraform v0.14.9

+ provider registry.terraform.io/hashicorp/aws v3.59.0

## Reproduction

I am using workspaces and I've attempted this terraform init after deleting the .terraform directory.

### Code Snippet to Reproduce

```
module "records" {
  source = "https://github.com/terraform-aws-modules/terraform-aws-route53.git"
  zone_id = var.zone_id
  records = [
     {
      name           = var.record_name
      type           = "CNAME"
      ttl            = 5
      records        = var.records
      set_identifier = var.identifier
      weighted_routing_policy = {
        weight = 100
      }
     }
  ]
}

```

## Expected behavior
I expect terraform to clone the module and utilize it.

## Actual behavior
Error: Failed to download module

Could not download module "records" (main.tf:26) source code from
"https://github.com/terraform-aws-modules/terraform-aws-route53.git": error
downloading
'https://github.com/terraform-aws-modules/terraform-aws-route53.git': no
source URL was returned

**Comment by antonbabenko** [comment]
Please check Terraform docs about modules sources - https://www.terraform.io/docs/language/modules/sources.html
