### ISSUE TITLE
Add prevent_destroy to zone's module.

### ISSUE THREAD

**Issue by IlitoAgrolend** [terraform-aws-modules/terraform-aws-route53#61]
## Is this feature available in the AWS provider for Terraform?
Yes, https://www.terraform.io/docs/language/meta-arguments/lifecycle.html

## Is your request related to a problem? Please describe.
Accidental or malicious deletion of DNS records is one important cause of IT service unavailability. For instance, if a DNS record is deleted from a domain controller, users might not be able to log in or access the service. It would be safer if there was an option to enable the prevent_destroy option by default in the aws_route53_one resource 

## Describe the solution you'd like.
An option to enable the _prevent_destroy_ option by default in the _aws_route53_one_ resource

## Describe alternatives you've considered.
Add to zone's module this option:
```
lifecycle {
    prevent_destroy = var.prevent_destroy
  }
```
## Additional context
n/a

**Comment by antonbabenko** [comment]
Hi @IlitoAgrolend !

Terraform does not allow us to use variables in `lifecycle`, so we can't make it work for everyone.

Closing this issue.
