### ISSUE TITLE
Support Lifecycle config in modules

### ISSUE THREAD

**Issue by shiron-babi** [terraform-aws-modules/terraform-aws-route53#63]
## Is your request related to a new offering from AWS?
No.

## Is your request related to a problem? Please describe.
It will be great if we could support lifecycle configuration within the modules.

## Describe the solution you'd like.
Something like:
```
  lifecycle {
    ignore_changes = var.ignore_changes
  }
```

## Describe alternatives you've considered.
N/A

## Additional context
N/A

**Comment by antonbabenko** [comment]
Terraform does not allow variables inside `lifecycle` blocks.
