### ISSUE TITLE
Proposal: To delete data resource from records module

### ISSUE THREAD

**Issue by marko-roman** [terraform-aws-modules/terraform-aws-route53#71]
What i propose:
to delete data resource, and pass `zone_id` through global variable,

Why i want to do this:
for example i want to create infrastructure use with `terragrunt`
example of the structure:
```
|_domain.example
   |_zone
   |_records
```
Where `record` depends on `zone`
And when i try to run `plan` or `apply` i get error 
```
╷
│ Error: no matching Route53Zone found
│ 
│   with data.aws_route53_zone.this[0],
│   on main.tf line 23, in data "aws_route53_zone" "this":
│   23: data "aws_route53_zone" "this" {
│ 
```
How do you think, maybe better way it is to pass zone_id to this module through variable?

I have not a lot of experience in this, but it is just proposal.

**Comment by antonbabenko** [comment]
You can specify `zone_id` or `zone_name`. The module will get the values of both attributes from the AWS Route53 service (`name` and `zone_id`) to make records.

If you are using terragrunt, you have to use `dependency` in `_records/terragrunt.hcl` file. For example:

```hcl
terraform {
  source = "tfr:///terraform-aws-modules/route53/aws//modules/records?version=2.0.0"
}

include {
  path = find_in_parent_folders()
}

dependency "zone" {
  config_path = "../zone"
}

inputs = {

  zone_name = keys(dependency.zone.outputs.route53_zone_name)[0]  # <= this is it

  records = [
    {
      name = ""
      type = "A"
      alias = {
        name    = dependency.dev-cloudfront.outputs.cloudfront_distribution_domain_name
        zone_id = dependency.dev-cloudfront.outputs.cloudfront_distribution_hosted_zone_id
      }
    }
  ]
}
```

Please ask Terragrunt-related questions here - https://github.com/gruntwork-io/terragrunt/issues
