### ISSUE TITLE
[Module 'Records'] Add support for Latency routing policies

### ISSUE THREAD

**Issue by g4rb1** [terraform-aws-modules/terraform-aws-route53#75]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: [AWS provider resource details](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_record#latency_routing_policy)

## Is your request related to a problem? Please describe.

I cannot import the already created records into the module since all of them use a latency routing policy to find the nearest region

## Describe the solution you'd like.

Just add an extra input for the required routing policy

## Describe alternatives you've considered.

The only workaround would be not using this module for records that need this kind of policy

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.9.0 :tada:
