### ISSUE TITLE
Avoid records re-creation imposed by data.aws_route53_zone.this

### ISSUE THREAD

**Issue by Roxyrob** [terraform-aws-modules/terraform-aws-route53#78]
Using depends_on in terraform configuration that source records module, will propagate depends_on to data source used to get zone_id by zone_name. This impose records recreation like seen in [AWS Route 53 record recreation](https://github.com/hashicorp/terraform-provider-aws/issues/64#issuecomment-351154030)

**citation**: `This forces the data source to in a sense be marked as something that can't be known until apply time. As a result, Terraform must plan on the ZoneID changing`

This is the code identified in record module:

```
data "aws_route53_zone" "this" {
  count = var.create && (var.zone_id != null || var.zone_name != null) ? 1 : 0

  zone_id      = var.zone_id
  name         = var.zone_name
  private_zone = var.private_zone
}
```

This happen expecially if we use a map of "zones" =>{ record = [{...}]} with multiple zones as keys. Removing one zone in the variable will produce a re-creation of all records in all other zones.

Unfortunately in some configuration we tried introducing implicit dependency like this below but this doesn't works (not really clear why):

```
resource "aws_route53_zone" "route53_phz" {
...
}

module "records" {
  source = "../../modules/records"

  zone_name = aws_route53_zone.route53_phz.name
...
```
## Describe the solution you'd like.
Unkown.

I ask you how to call your records module so it can be dependent by zone non created by your zone module without using depends_on and without create resources in sequence to avoid error:
```
│ Error: no matching Route53Zone found
│   with ...data.aws_route53_zone.this[0],
│   on .../modules/records/main.tf line 10, in data "aws_route53_zone" "this":
│   10: data "aws_route53_zone" "this" {
```

## Describe alternatives you've considered.

- 2 step apply (first) create zone (second) create records
- depends_on but this impose uselessly record re-creation (sometime many records - aws is slow on records management)

**Comment by Roxyrob** [comment]
As a workaround on the way to use Hybrid DNS centralization, I created hosted zones into accountB route53 using management accountA terraform configuration, leaving to accountB records creation (e.g. EC2 on accuontB auto registration, etc.). This splitted configuration avoid the dependency or re-creation issue imposing hosted zone before records creation.

Anyway, I'm interested if you know solutions for this issue not based on 2 step apply.

**Comment by stephgosling** [comment]
Another datum

Have just run into this today, what's very curious is that this did work for me in the past (with 2.0.0 of the module, aws provider 3.42.0, terraform 0.14.7 and terragrunt 0.28.7) however with 2.9.0,4.30,1.2.8 and 0.38.9

Consider the following terragrunt snippet:
```
terraform {
  source = "github.com/terraform-aws-modules/terraform-aws-route53.git//modules/records?ref=v2.9.0"
}

dependency "zone" {
  config_path = "../zone"
}

dependency "delegate-dev" {
  config_path = "${get_parent_terragrunt_dir()}/account1/r53/dev.${local.project.inputs.name}/zone"
}
#
dependency "delegate-test" {
  config_path = "${get_parent_terragrunt_dir()}/account2/test.${local.project.inputs.name}/zone"
}

inputs = merge(
  local.project.inputs,
  {
    #zone_id = "Z059542693SIULH86GBT"
   zone_id = dependency.zone.outputs.route53_zone_zone_id

   records = [
      {
        name    = "dev"
        type    = "NS"
        ttl     = 7200
        records = dependency.delegate-dev.outputs.route53_zone_name_servers
      },
      {
        name    = "test"
        type    = "NS"
        ttl     = 7200
        records = dependency.delegate-test.outputs.route53_zone_name_servers
      }
    ]
  }
)
```
Results in
```
data.aws_route53_zone.this[0]: Reading...
╷
│ Error: no matching Route53Zone found
│ 
│   with data.aws_route53_zone.this[0],
│   on main.tf line 10, in data "aws_route53_zone" "this":
│   10: data "aws_route53_zone" "this" {
│ 
╵
```

The thing that _really_ baffles me is that hardcoding the zone_id works when in principle it shouldn't need to calculate it as terragrunt has done all that already (well has read the remote state for `dependency.zone`

**Comment by antonbabenko** [comment]
@stephgosling In fact, this issue is pretty easy to fix, but the user will have to provide `zone_id` and `zone_name`.

I will reopen this issue but can't guarantee when I have time for this myself, so PR is welcome.

**Comment by stephgosling** [comment]
at the moment it seems to be `zone_id` xor `zone_name`. Gotta get the kids but will have a look :+1:

**Comment by stephgosling** [comment]
The problem with the user passing both is `Error: zone_id and name arguments can't be used together` because [as the docs say: `You have to use zone_id or name, not both of them`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/route53_zone); I'm still trying to get my head round why it works with terragrunt if the terragrunt input is hardcoded versus from the dependency

**Comment by stephgosling** [comment]
@antonbabenko ignore me. PEBCAK. Keep forgetting that route53_zone_zone_id is now a map.

**Comment by cbernet** [comment]
Thanks a lot, you solved my problem. 

I did the following : 

* do not specify zone_name
* specify : 

```
  zone_id = module.my_zones.route53_zone_zone_id["my_zone_name"]
```
