### ISSUE TITLE
Add mx and txt examples

### ISSUE THREAD

**Issue by mnichols62** [terraform-aws-modules/terraform-aws-route53#79]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
I'm unable to get the correct formatting for multiple MX and TXT records

## Describe the solution you'd like.
Please update the complete example to include samples with the correct formats for multiple records of these types.

## Describe alternatives you've considered.
I tried adding set_identifiers to the records, but that didn't work.

## Additional context
 Error: Duplicate object key
│
│   on ../modules/records/main.tf line 7, in locals:
│    7:   recordsets = { for rs in local.records : try(rs.key, join(" ", compact(["${rs.name} ${rs.type}", try(rs.set_identifier, "")]))) => rs }
│     ├────────────────
│     │ rs.name is ""
│     │ rs.type is "TXT"
│
│ Two different items produced the key " TXT" in this 'for' expression. If duplicates are expected, use the ellipsis
│ (...) after the value expression to enable grouping by key.
╵
╷

**Comment by antonbabenko** [comment]
Please fill in the issue template and take a look at the code in `examples`. Using different values in `key` attribute will make it work - see [this line](https://github.com/terraform-aws-modules/terraform-aws-route53/blob/master/examples/complete/main.tf#L68).

**Comment by mnichols62** [comment]
The documentation on the usage of "keys" is not clear. Both TXT and MX records can be entered as arrays as shown with CNAMES. How does varying the keys create multiple TXT records?

**Comment by antonbabenko** [comment]
`key` is helpful to make sure that each item is unique&computed.

Please provide the input values you are trying to use (aka "fill in the issue template"). It is very hard for maintainers to help without knowing more.
