### ISSUE TITLE
Example doesn't work for me

### ISSUE THREAD

**Issue by solidnerd** [terraform-aws-modules/terraform-aws-route53#8]
Hey, 
I tried to do the example but I got the following error:

```sh
$ terraform plan
Error: Reserved argument name in module block

  on dns.tf line 43, in module "records":
  43:   depends_on = [module.zones]

The name "depends_on" is reserved for use in a future version of Terraform.

```

**Comment by deyceg** [comment]
@solidnerd you need to uprade to terraform 0.13.x or remove the `depends_on` stanza from the module its not fully supported yet.

**Comment by antonbabenko** [comment]
As @deyceg says - Terraform 0.13 is required for this module.

Closing this issue.
