### ISSUE TITLE
Unable to pass 2 different zone_ids (private and public) in a single module call

### ISSUE THREAD

**Issue by ashishjullia** [terraform-aws-modules/terraform-aws-route53#81]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [ yes] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version: 
Terraform v1.1.9

- Provider version(s):
Terraform v1.1.9
on linux_amd64 + provider registry.terraform.io/hashicorp/aws v4.25.0

## Reproduction Code [Required]
```
module "records" {
  source  = "terraform-aws-modules/route53/aws//modules/records"
  version = "~> 2.0"

  zone_id = "<zone-id-1>"

  records = [
    {
      name    = "example-test-1"
      type    = "CNAME"
      ttl     = 3600
      records = [
        "10.10.10.10",
      ]
    }
  ]


  zone_id = "<zone-id-2>"
  private_zone = true

  records = [
    {
      name    = "example-test-1"
      type    = "CNAME"
      ttl     = 3600
      records = [
        "10.10.10.20",
      ]
    }
  ]
}
```

terraform apply

## Expected behavior
There is a record name "example-test-1" and I want to create entry for it for 2 hosted zone, one is public and other is private.

## Actual behavior
Unable to find a way to perform this.

## Additional context
I am not able to figure out how to provide 2 different `zone_id(s)` in the same module block, one with passing `private_zone = true` and other without it (public).

**Comment by SolidSly** [comment]
Hello @ashishjullia,
I don't think it is possible to create records for two different zones in the way you describe it.
More precisely, it is not possible to do it using only one time the module.

You should use the module one time per zone to use. In your example, your should use the module one time for the public zone and one time for the private zone. It should look something like this:

```
module "records_zone_public" {
  source  = "terraform-aws-modules/route53/aws//modules/records"
  version = "~> 2.0"

  zone_id = "<zone-id-1>"

  records = [
    {
      name    = "example-test-1"
      type    = "CNAME"
      ttl     = 3600
      records = [
        "10.10.10.10",
      ]
    }
  ]
}

module "records_zone_private" {
  source  = "terraform-aws-modules/route53/aws//modules/records"
  version = "~> 2.0"

  zone_id = "<zone-id-2>"
  private_zone = true

  records = [
    {
      name    = "example-test-1"
      type    = "CNAME"
      ttl     = 3600
      records = [
        "10.10.10.20",
      ]
    }
  ]
}
```

**Comment by ashishjullia** [comment]
Yup, that's completely correct.

Thanks.

Closing.
