### ISSUE TITLE
Modifying record type causes the record to be deleted and recreated

### ISSUE THREAD

**Issue by sumeetgn** [terraform-aws-modules/terraform-aws-route53#95]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? 
  - Yes ✅

## Is your request related to a problem? Please describe.
When updating the type of a route53 record, the record gets deleted and recreated. This causes the domain to be unavailable for some time.
This is because recordset name is [created](https://github.com/terraform-aws-modules/terraform-aws-route53/blob/d67ac59473bf3eb2628c30b2f26cb743dd3580ed/modules/records/main.tf#L7) by concatenating name and type of record.

**Comment by antonbabenko** [comment]
It is done this way on purpose. Changing type means that the old record should be deleted before creating new one.
